
name: AWS Sample
label: aws_sample
description: AWS Sample
type: terraform
extends:

#access_key="{{ aws_access_key }}"
#secret_key="{{ aws_secret_key }}"
#pavm_key_name="{{ aws_key_pair_name }}"
#pavm_key_path="{{ aws_key_path }}"
#region="{{ aws_region }}"
#availability_zone="{{ aws_az }}"
#pavm_bootstrap_s3="{{ bootstrap_s3_name }}"

labels:
  service_type: aws_terraform

variables:
  - name: aws_key
    description: AWS Access Key
    default: access_key
    type_hint: text
  - name: aws_secret
    description: aws_secret_key
    default: secret
    type_hint: password
  - name: pavm_key_name
    description: SSH Key Name
    default: ssh_key_pair
    type_hint: text
  - name: aws_key_path
    description: Local SSH Key Path
    default: ssh_key_path
    type_hint: text
  - name: region
    description: AWS Region
    default: us-east-2
    type_hint: text
  - name: availability_zone
    description: AWS Availability Zone
    default: us-east-2b
    type_hint: text
  - name: pavm_bootstrap_s3
    description: Bootstrap S3 Bucket Name
    default: s3-something
    type_hint: text

snippets:
  - name: tfvars
    file: terraform.tfvars.j2
    dest: terraform.tfvars
